import VerticalNavbar from '@/components/Navbar/VerticalNavbar';
import './globals.css';
import { Inter, Cormorant_Garamond  } from 'next/font/google';
import HorizontalNavbar from '@/components/Navbar/HorizontalNavbar';

const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="main-section">
          
          <div className="main-vertical">
            <VerticalNavbar />
          </div>

          <div className="main-horizontal">
            <HorizontalNavbar />
          </div>
          
        </div>
        <div className="body-content">{children}</div>
      </body>
    </html>
  );
}
