# Generated by Django 4.2.4 on 2023-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaff',
            name='password',
            field=models.CharField(default='booran', max_length=100),
        ),
    ]
