# Generated by Django 4.2.4 on 2023-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adminstaff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default='booran', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='booran', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='booran', max_length=100),
        ),
    ]
